from pathlib import Path

from word_madness_bot.application.solution_planning import LevelSolutionPlan
from word_madness_bot.application.word_execution import SingleWordExecutor
from word_madness_bot.application.ports.android import AndroidPort